  File "/usr/lib/python3/site-packages/_pytest/main.py", line 283 in wrap_session
  File "/usr/lib/python3/site-packages/_pytest/main.py", line 330 in pytest_cmdline_main
  File "/usr/lib/python3/site-packages/pluggy/_callers.py", line 103 in _multicall
  File "/usr/lib/python3/site-packages/pluggy/_manager.py", line 120 in _hookexec
  File "/usr/lib/python3/site-packages/pluggy/_hooks.py", line 513 in __call__
  File "/usr/lib/python3/site-packages/_pytest/config/__init__.py", line 175 in main
  File "/usr/lib/python3/site-packages/_pytest/config/__init__.py", line 201 in console_main
  File "/usr/bin/py.test3", line 9 in <module>

hasher-privd: parent: handle_io: idle time limit (3600 seconds) exceeded
hsh-rebuild: rebuild of `python3-module-pyqtgraph-0.12.4-alt1.3.src.rpm' failed.
Command exited with non-zero status 1
5.53user 4.27system 1:04:14elapsed 0%CPU (0avgtext+0avgdata 133160maxresident)k
226960inputs+0outputs (0major+454688minor)pagefaults 0swaps
